/*
 * ZaListLang.cpp
 *
 *  Created on: 2012-10-2
 *      Author: Administrator
 */

#include "ZaListLang.h"
#include <sys/stat.h>
namespace bbcubezone {

ZaListLang::ZaListLang() {
	// TODO Auto-generated constructor stub
	m_style= 0;
}

void ZaListLang::init()
{
	m_v.push_back("Abkhazian");
	m_v.push_back("Afar");
	m_v.push_back("Afrikaans");
	m_v.push_back("Albanian");
	m_v.push_back("Amharic");
	m_v.push_back("Arabic");
	m_v.push_back("Armenian");
	m_v.push_back("Assamese");
	m_v.push_back("Aymara");
	m_v.push_back("Azerbaijani");
	m_v.push_back("Bashkir");
	m_v.push_back("Basque");
	m_v.push_back("Bengali (Bangla)");
	m_v.push_back("Bhutani");
	m_v.push_back("Bihari");
	m_v.push_back("Bislama");
	m_v.push_back("Breton");
	m_v.push_back("Bulgarian");
	m_v.push_back("Burmese");
	m_v.push_back("Byelorussian (Belarusian)");
	m_v.push_back("Cambodian");
	m_v.push_back("Catalan");
	m_v.push_back("Cherokee");
	m_v.push_back("Chewa");
	m_v.push_back("Chinese (Simplified)");
	m_v.push_back("Chinese (Traditional)");
	m_v.push_back("Corsican");
	m_v.push_back("Croatian");
	m_v.push_back("Czech");
	m_v.push_back("Danish");
	m_v.push_back("Divehi");
	m_v.push_back("Dutch");
	m_v.push_back("Edo");
	m_v.push_back("English");
	m_v.push_back("Esperanto");
	m_v.push_back("Estonian");
	m_v.push_back("Faeroese");
	m_v.push_back("Farsi");
	m_v.push_back("Fiji");
	m_v.push_back("Finnish");
	m_v.push_back("Flemish");
	m_v.push_back("French");
	m_v.push_back("Frisian");
	m_v.push_back("Fulfulde");
	m_v.push_back("Galician");
	m_v.push_back("Gaelic (Scottish)");
	m_v.push_back("Gaelic (Manx)");
	m_v.push_back("Georgian");
	m_v.push_back("German");
	m_v.push_back("Greek");
	m_v.push_back("Greenlandic");
	m_v.push_back("Guarani");
	m_v.push_back("Gujarati");
	m_v.push_back("Hausa");
	m_v.push_back("Hawaiian");
	m_v.push_back("Hebrew");
	m_v.push_back("Hindi");
	m_v.push_back("Hungarian");
	m_v.push_back("Ibibio");
	m_v.push_back("Icelandic");
	m_v.push_back("Igbo");
	m_v.push_back("Indonesian");
	m_v.push_back("Interlingua");
	m_v.push_back("Interlingue");
	m_v.push_back("Inuktitut");
	m_v.push_back("Inupiak");
	m_v.push_back("Irish");
	m_v.push_back("Italian");
	m_v.push_back("Japanese");
	m_v.push_back("Javanese");
	m_v.push_back("Kannada");
	m_v.push_back("Kanuri");
	m_v.push_back("Kashmiri");
	m_v.push_back("Kazakh");
	m_v.push_back("Kinyarwanda (Ruanda)");
	m_v.push_back("Kirghiz");
	m_v.push_back("Kirundi (Rundi)");
	m_v.push_back("Konkani");
	m_v.push_back("Korean");
	m_v.push_back("Kurdish");
	m_v.push_back("Laothian");
	m_v.push_back("Latin");
	m_v.push_back("Latvian (Lettish)");
	m_v.push_back("Limburgish ( Limburger)");
	m_v.push_back("Lingala");
	m_v.push_back("Lithuanian");
	m_v.push_back("Macedonian");
	m_v.push_back("Malagasy");
	m_v.push_back("Malay");
	m_v.push_back("Malayalam");
	m_v.push_back("Maltese");
	m_v.push_back("Maori");
	m_v.push_back("Marathi");
	m_v.push_back("Moldavian");
	m_v.push_back("Mongolian");
	m_v.push_back("Nauru");
	m_v.push_back("Nepali");
	m_v.push_back("Norwegian");
	m_v.push_back("Occitan");
	m_v.push_back("Oriya");
	m_v.push_back("Oromo (Afan, Galla)");
	m_v.push_back("Papiamentu");
	m_v.push_back("Pashto (Pushto)");
	m_v.push_back("Polish");
	m_v.push_back("Portuguese");
	m_v.push_back("Punjabi");
	m_v.push_back("Quechua");
	m_v.push_back("Rhaeto-Romance");
	m_v.push_back("Romanian");
	m_v.push_back("Russian");
	m_v.push_back("Sami (Lappish)");
	m_v.push_back("Samoan");
	m_v.push_back("Sangro");
	m_v.push_back("Sanskrit");
	m_v.push_back("Serbian");
	m_v.push_back("Serbo-Croatian");
	m_v.push_back("Sesotho");
	m_v.push_back("Setswana");
	m_v.push_back("Shona");
	m_v.push_back("Sindhi");
	m_v.push_back("Sinhalese");
	m_v.push_back("Siswati");
	m_v.push_back("Slovak");
	m_v.push_back("Slovenian");
	m_v.push_back("Somali");
	m_v.push_back("Spanish");
	m_v.push_back("Sundanese");
	m_v.push_back("Swahili (Kiswahili)");
	m_v.push_back("Swedish");
	m_v.push_back("Syriac");
	m_v.push_back("Tagalog");
	m_v.push_back("Tajik");
	m_v.push_back("Tamazight");
	m_v.push_back("Tamil");
	m_v.push_back("Tatar");
	m_v.push_back("Telugu");
	m_v.push_back("Thai");
	m_v.push_back("Tibetan");
	m_v.push_back("Tigrinya");
	m_v.push_back("Tonga");
	m_v.push_back("Tsonga");
	m_v.push_back("Turkish");
	m_v.push_back("Turkmen");
	m_v.push_back("Twi");
	m_v.push_back("Uighur");
	m_v.push_back("Ukrainian");
	m_v.push_back("Urdu");
	m_v.push_back("Uzbek");
	m_v.push_back("Venda");
	m_v.push_back("Vietnamese");
	m_v.push_back("Volapuk");
	m_v.push_back("Welsh");
	m_v.push_back("Wolof");
	m_v.push_back("Xhosa");
	m_v.push_back("Yi");
	m_v.push_back("Yiddish");
	m_v.push_back("Yoruba");
	m_v.push_back("Zulu");

	m_lang.push_back("ab");
	m_lang.push_back("aa");
	m_lang.push_back("af");
	m_lang.push_back("sq");
	m_lang.push_back("am");
	m_lang.push_back("ar");
	m_lang.push_back("hy");
	m_lang.push_back("as");
	m_lang.push_back("ay");
	m_lang.push_back("az");
	m_lang.push_back("ba");
	m_lang.push_back("eu");
	m_lang.push_back("bn");
	m_lang.push_back("dz");
	m_lang.push_back("bh");
	m_lang.push_back("bi");
	m_lang.push_back("br");
	m_lang.push_back("bg");
	m_lang.push_back("my");
	m_lang.push_back("be");
	m_lang.push_back("km");
	m_lang.push_back("ca");
	m_lang.push_back("");
	m_lang.push_back("");
	m_lang.push_back("zh");
	m_lang.push_back("zh");
	m_lang.push_back("co");
	m_lang.push_back("hr");
	m_lang.push_back("cs");
	m_lang.push_back("da");
	m_lang.push_back("");
	m_lang.push_back("nl");
	m_lang.push_back("");
	m_lang.push_back("en");
	m_lang.push_back("eo");
	m_lang.push_back("et");
	m_lang.push_back("fo");
	m_lang.push_back("fa");
	m_lang.push_back("fj");
	m_lang.push_back("fi");
	m_lang.push_back("");
	m_lang.push_back("fr");
	m_lang.push_back("fy");
	m_lang.push_back("");
	m_lang.push_back("gl");
	m_lang.push_back("gd");
	m_lang.push_back("gv");
	m_lang.push_back("ka");
	m_lang.push_back("de");
	m_lang.push_back("el");
	m_lang.push_back("kl");
	m_lang.push_back("gn");
	m_lang.push_back("gu");
	m_lang.push_back("ha");
	m_lang.push_back("");
	m_lang.push_back("he");//, iw
	m_lang.push_back("hi");
	m_lang.push_back("hu");
	m_lang.push_back("");
	m_lang.push_back("is");
	m_lang.push_back("");
	m_lang.push_back("id");//, in
	m_lang.push_back("ia");
	m_lang.push_back("ie");
	m_lang.push_back("iu");
	m_lang.push_back("ik");
	m_lang.push_back("ga");
	m_lang.push_back("it");
	m_lang.push_back("ja");
	m_lang.push_back("jv");
	m_lang.push_back("kn");
	m_lang.push_back("");
	m_lang.push_back("ks");
	m_lang.push_back("kk");
	m_lang.push_back("rw");
	m_lang.push_back("ky");
	m_lang.push_back("rn");
	m_lang.push_back("");
	m_lang.push_back("ko");
	m_lang.push_back("ku");
	m_lang.push_back("lo");
	m_lang.push_back("la");
	m_lang.push_back("lv");
	m_lang.push_back("li");
	m_lang.push_back("ln");
	m_lang.push_back("lt");
	m_lang.push_back("mk");
	m_lang.push_back("mg");
	m_lang.push_back("ms");
	m_lang.push_back("ml");
	m_lang.push_back("mt");
	m_lang.push_back("mi");
	m_lang.push_back("mr");
	m_lang.push_back("mo");
	m_lang.push_back("mn");
	m_lang.push_back("na");
	m_lang.push_back("ne");
	m_lang.push_back("no");
	m_lang.push_back("oc");
	m_lang.push_back("or");
	m_lang.push_back("om");
	m_lang.push_back("");
	m_lang.push_back("ps");
	m_lang.push_back("pl");
	m_lang.push_back("pt");
	m_lang.push_back("pa");
	m_lang.push_back("qu");
	m_lang.push_back("rm");
	m_lang.push_back("ro");
	m_lang.push_back("ru");
	m_lang.push_back("");
	m_lang.push_back("sm");
	m_lang.push_back("sg");
	m_lang.push_back("sa");
	m_lang.push_back("sr");
	m_lang.push_back("sh");
	m_lang.push_back("st");
	m_lang.push_back("tn");
	m_lang.push_back("sn");
	m_lang.push_back("sd");
	m_lang.push_back("si");
	m_lang.push_back("ss");
	m_lang.push_back("sk");
	m_lang.push_back("sl");
	m_lang.push_back("so");
	m_lang.push_back("es");
	m_lang.push_back("su");
	m_lang.push_back("sw");
	m_lang.push_back("sv");
	m_lang.push_back("");
	m_lang.push_back("tl");
	m_lang.push_back("tg");
	m_lang.push_back("");
	m_lang.push_back("ta");
	m_lang.push_back("tt");
	m_lang.push_back("te");
	m_lang.push_back("th");
	m_lang.push_back("bo");
	m_lang.push_back("ti");
	m_lang.push_back("to");
	m_lang.push_back("ts");
	m_lang.push_back("tr");
	m_lang.push_back("tk");
	m_lang.push_back("tw");
	m_lang.push_back("ug");
	m_lang.push_back("uk");
	m_lang.push_back("ur");
	m_lang.push_back("uz");
	m_lang.push_back("");
	m_lang.push_back("vi");
	m_lang.push_back("vo");
	m_lang.push_back("cy");
	m_lang.push_back("wo");
	m_lang.push_back("xh");
	m_lang.push_back("");
	m_lang.push_back("yi");//, ji
	m_lang.push_back("yo");
	m_lang.push_back("zu");

	m_top = m_height;
}


ZaListLang::~ZaListLang() {
	// TODO Auto-generated destructor stub

}

} /* namespace bbcubezone */
